### ISSUE TITLE
mission6.so missing libcifer.so

### ISSUE THREAD

**Issue by SaintJackson** [cryptohackathon/IPFE-py#1]
When i run the following command:

ldd mission6.so

Then it returns libcifer.so file is not there.

Where can I reach libcifer.so? And how to integrate it with this project?

**Comment by prajwalpanzade** [comment]
You'll have to first build the CiFEr from https://github.com/fentec-project/CiFEr. 

After build is successful, you'll get libcifer.so in the '/usr/local/lib. Then paste the same in the python lib directory.
